// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is AdyenPigeonError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): AdyenPigeonError {
  return AdyenPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class AdyenPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class Environment(val raw: Int) {
  TEST(0),
  EUROPE(1),
  UNITEDSTATES(2),
  AUSTRALIA(3),
  INDIA(4),
  APSE(5);

  companion object {
    fun ofRaw(raw: Int): Environment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AddressMode(val raw: Int) {
  FULL(0),
  POSTALCODE(1),
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): AddressMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CardAuthMethod(val raw: Int) {
  PANONLY(0),
  CRYPTOGRAM3DS(1);

  companion object {
    fun ofRaw(raw: Int): CardAuthMethod? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class TotalPriceStatus(val raw: Int) {
  NOTCURRENTLYKNOWN(0),
  ESTIMATED(1),
  FINALPRICE(2);

  companion object {
    fun ofRaw(raw: Int): TotalPriceStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class GooglePayEnvironment(val raw: Int) {
  TEST(0),
  PRODUCTION(1);

  companion object {
    fun ofRaw(raw: Int): GooglePayEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CashAppPayEnvironment(val raw: Int) {
  SANDBOX(0),
  PRODUCTION(1);

  companion object {
    fun ofRaw(raw: Int): CashAppPayEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PaymentResultEnum(val raw: Int) {
  CANCELLEDBYUSER(0),
  ERROR(1),
  FINISHED(2);

  companion object {
    fun ofRaw(raw: Int): PaymentResultEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformCommunicationType(val raw: Int) {
  PAYMENTCOMPONENT(0),
  ADDITIONALDETAILS(1),
  RESULT(2),
  DELETESTOREDPAYMENTMETHOD(3),
  BALANCECHECK(4),
  REQUESTORDER(5),
  CANCELORDER(6),
  BINLOOKUP(7);

  companion object {
    fun ofRaw(raw: Int): PlatformCommunicationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ComponentCommunicationType(val raw: Int) {
  ONSUBMIT(0),
  ADDITIONALDETAILS(1),
  LOADING(2),
  RESULT(3),
  RESIZE(4);

  companion object {
    fun ofRaw(raw: Int): ComponentCommunicationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PaymentEventType(val raw: Int) {
  FINISHED(0),
  ACTION(1),
  ERROR(2),
  UPDATE(3);

  companion object {
    fun ofRaw(raw: Int): PaymentEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class FieldVisibility(val raw: Int) {
  SHOW(0),
  HIDE(1);

  companion object {
    fun ofRaw(raw: Int): FieldVisibility? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class InstantPaymentType(val raw: Int) {
  GOOGLEPAY(0),
  APPLEPAY(1),
  INSTANT(2);

  companion object {
    fun ofRaw(raw: Int): InstantPaymentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ApplePayShippingType(val raw: Int) {
  SHIPPING(0),
  DELIVERY(1),
  STOREPICKUP(2),
  SERVICEPICKUP(3);

  companion object {
    fun ofRaw(raw: Int): ApplePayShippingType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ApplePayMerchantCapability(val raw: Int) {
  DEBIT(0),
  CREDIT(1);

  companion object {
    fun ofRaw(raw: Int): ApplePayMerchantCapability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ApplePaySummaryItemType(val raw: Int) {
  PENDING(0),
  DEFINITE(1);

  companion object {
    fun ofRaw(raw: Int): ApplePaySummaryItemType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CardNumberValidationResultDTO(val raw: Int) {
  VALID(0),
  INVALIDILLEGALCHARACTERS(1),
  INVALIDLUHNCHECK(2),
  INVALIDTOOSHORT(3),
  INVALIDTOOLONG(4),
  INVALIDOTHERREASON(5);

  companion object {
    fun ofRaw(raw: Int): CardNumberValidationResultDTO? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CardExpiryDateValidationResultDTO(val raw: Int) {
  VALID(0),
  INVALIDTOOFARINTHEFUTURE(1),
  INVALIDTOOOLD(2),
  NONPARSEABLEDATE(3),
  INVALIDOTHERREASON(4);

  companion object {
    fun ofRaw(raw: Int): CardExpiryDateValidationResultDTO? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CardSecurityCodeValidationResultDTO(val raw: Int) {
  VALID(0),
  INVALID(1);

  companion object {
    fun ofRaw(raw: Int): CardSecurityCodeValidationResultDTO? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SessionDTO (
  val id: String,
  val sessionData: String,
  val paymentMethodsJson: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): SessionDTO {
      val id = list[0] as String
      val sessionData = list[1] as String
      val paymentMethodsJson = list[2] as String
      return SessionDTO(id, sessionData, paymentMethodsJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      sessionData,
      paymentMethodsJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AmountDTO (
  val currency: String,
  val value: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): AmountDTO {
      val currency = list[0] as String
      val value = list[1].let { if (it is Int) it.toLong() else it as Long }
      return AmountDTO(currency, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      currency,
      value,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AnalyticsOptionsDTO (
  val enabled: Boolean,
  val version: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): AnalyticsOptionsDTO {
      val enabled = list[0] as Boolean
      val version = list[1] as String
      return AnalyticsOptionsDTO(enabled, version)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      enabled,
      version,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DropInConfigurationDTO (
  val environment: Environment,
  val clientKey: String,
  val countryCode: String,
  val amount: AmountDTO? = null,
  val shopperLocale: String? = null,
  val cardConfigurationDTO: CardConfigurationDTO? = null,
  val applePayConfigurationDTO: ApplePayConfigurationDTO? = null,
  val googlePayConfigurationDTO: GooglePayConfigurationDTO? = null,
  val cashAppPayConfigurationDTO: CashAppPayConfigurationDTO? = null,
  val analyticsOptionsDTO: AnalyticsOptionsDTO,
  val showPreselectedStoredPaymentMethod: Boolean,
  val skipListWhenSinglePaymentMethod: Boolean,
  val isRemoveStoredPaymentMethodEnabled: Boolean,
  val preselectedPaymentMethodTitle: String? = null,
  val paymentMethodNames: Map<String?, String?>? = null,
  val isPartialPaymentSupported: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DropInConfigurationDTO {
      val environment = Environment.ofRaw(list[0] as Int)!!
      val clientKey = list[1] as String
      val countryCode = list[2] as String
      val amount: AmountDTO? = (list[3] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      val shopperLocale = list[4] as String?
      val cardConfigurationDTO: CardConfigurationDTO? = (list[5] as List<Any?>?)?.let {
        CardConfigurationDTO.fromList(it)
      }
      val applePayConfigurationDTO: ApplePayConfigurationDTO? = (list[6] as List<Any?>?)?.let {
        ApplePayConfigurationDTO.fromList(it)
      }
      val googlePayConfigurationDTO: GooglePayConfigurationDTO? = (list[7] as List<Any?>?)?.let {
        GooglePayConfigurationDTO.fromList(it)
      }
      val cashAppPayConfigurationDTO: CashAppPayConfigurationDTO? = (list[8] as List<Any?>?)?.let {
        CashAppPayConfigurationDTO.fromList(it)
      }
      val analyticsOptionsDTO = AnalyticsOptionsDTO.fromList(list[9] as List<Any?>)
      val showPreselectedStoredPaymentMethod = list[10] as Boolean
      val skipListWhenSinglePaymentMethod = list[11] as Boolean
      val isRemoveStoredPaymentMethodEnabled = list[12] as Boolean
      val preselectedPaymentMethodTitle = list[13] as String?
      val paymentMethodNames = list[14] as Map<String?, String?>?
      val isPartialPaymentSupported = list[15] as Boolean
      return DropInConfigurationDTO(environment, clientKey, countryCode, amount, shopperLocale, cardConfigurationDTO, applePayConfigurationDTO, googlePayConfigurationDTO, cashAppPayConfigurationDTO, analyticsOptionsDTO, showPreselectedStoredPaymentMethod, skipListWhenSinglePaymentMethod, isRemoveStoredPaymentMethodEnabled, preselectedPaymentMethodTitle, paymentMethodNames, isPartialPaymentSupported)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      environment.raw,
      clientKey,
      countryCode,
      amount?.toList(),
      shopperLocale,
      cardConfigurationDTO?.toList(),
      applePayConfigurationDTO?.toList(),
      googlePayConfigurationDTO?.toList(),
      cashAppPayConfigurationDTO?.toList(),
      analyticsOptionsDTO.toList(),
      showPreselectedStoredPaymentMethod,
      skipListWhenSinglePaymentMethod,
      isRemoveStoredPaymentMethodEnabled,
      preselectedPaymentMethodTitle,
      paymentMethodNames,
      isPartialPaymentSupported,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CardConfigurationDTO (
  val holderNameRequired: Boolean,
  val addressMode: AddressMode,
  val showStorePaymentField: Boolean,
  val showCvcForStoredCard: Boolean,
  val showCvc: Boolean,
  val kcpFieldVisibility: FieldVisibility,
  val socialSecurityNumberFieldVisibility: FieldVisibility,
  val supportedCardTypes: List<String?>

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): CardConfigurationDTO {
      val holderNameRequired = list[0] as Boolean
      val addressMode = AddressMode.ofRaw(list[1] as Int)!!
      val showStorePaymentField = list[2] as Boolean
      val showCvcForStoredCard = list[3] as Boolean
      val showCvc = list[4] as Boolean
      val kcpFieldVisibility = FieldVisibility.ofRaw(list[5] as Int)!!
      val socialSecurityNumberFieldVisibility = FieldVisibility.ofRaw(list[6] as Int)!!
      val supportedCardTypes = list[7] as List<String?>
      return CardConfigurationDTO(holderNameRequired, addressMode, showStorePaymentField, showCvcForStoredCard, showCvc, kcpFieldVisibility, socialSecurityNumberFieldVisibility, supportedCardTypes)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      holderNameRequired,
      addressMode.raw,
      showStorePaymentField,
      showCvcForStoredCard,
      showCvc,
      kcpFieldVisibility.raw,
      socialSecurityNumberFieldVisibility.raw,
      supportedCardTypes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApplePayConfigurationDTO (
  val merchantId: String,
  val merchantName: String,
  val allowOnboarding: Boolean? = null,
  val summaryItems: List<ApplePaySummaryItemDTO?>? = null,
  val requiredBillingContactFields: List<String?>? = null,
  val billingContact: ApplePayContactDTO? = null,
  val requiredShippingContactFields: List<String?>? = null,
  val shippingContact: ApplePayContactDTO? = null,
  val applePayShippingType: ApplePayShippingType? = null,
  val allowShippingContactEditing: Boolean? = null,
  val shippingMethods: List<ApplePayShippingMethodDTO?>? = null,
  val applicationData: String? = null,
  val supportedCountries: List<String?>? = null,
  val merchantCapability: ApplePayMerchantCapability? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ApplePayConfigurationDTO {
      val merchantId = list[0] as String
      val merchantName = list[1] as String
      val allowOnboarding = list[2] as Boolean?
      val summaryItems = list[3] as List<ApplePaySummaryItemDTO?>?
      val requiredBillingContactFields = list[4] as List<String?>?
      val billingContact: ApplePayContactDTO? = (list[5] as List<Any?>?)?.let {
        ApplePayContactDTO.fromList(it)
      }
      val requiredShippingContactFields = list[6] as List<String?>?
      val shippingContact: ApplePayContactDTO? = (list[7] as List<Any?>?)?.let {
        ApplePayContactDTO.fromList(it)
      }
      val applePayShippingType: ApplePayShippingType? = (list[8] as Int?)?.let {
        ApplePayShippingType.ofRaw(it)
      }
      val allowShippingContactEditing = list[9] as Boolean?
      val shippingMethods = list[10] as List<ApplePayShippingMethodDTO?>?
      val applicationData = list[11] as String?
      val supportedCountries = list[12] as List<String?>?
      val merchantCapability: ApplePayMerchantCapability? = (list[13] as Int?)?.let {
        ApplePayMerchantCapability.ofRaw(it)
      }
      return ApplePayConfigurationDTO(merchantId, merchantName, allowOnboarding, summaryItems, requiredBillingContactFields, billingContact, requiredShippingContactFields, shippingContact, applePayShippingType, allowShippingContactEditing, shippingMethods, applicationData, supportedCountries, merchantCapability)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      merchantId,
      merchantName,
      allowOnboarding,
      summaryItems,
      requiredBillingContactFields,
      billingContact?.toList(),
      requiredShippingContactFields,
      shippingContact?.toList(),
      applePayShippingType?.raw,
      allowShippingContactEditing,
      shippingMethods,
      applicationData,
      supportedCountries,
      merchantCapability?.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApplePayContactDTO (
  val phoneNumber: String? = null,
  val emailAddress: String? = null,
  val givenName: String? = null,
  val familyName: String? = null,
  val phoneticGivenName: String? = null,
  val phoneticFamilyName: String? = null,
  val addressLines: List<String?>? = null,
  val subLocality: String? = null,
  val city: String? = null,
  val postalCode: String? = null,
  val subAdministrativeArea: String? = null,
  val administrativeArea: String? = null,
  val country: String? = null,
  val countryCode: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ApplePayContactDTO {
      val phoneNumber = list[0] as String?
      val emailAddress = list[1] as String?
      val givenName = list[2] as String?
      val familyName = list[3] as String?
      val phoneticGivenName = list[4] as String?
      val phoneticFamilyName = list[5] as String?
      val addressLines = list[6] as List<String?>?
      val subLocality = list[7] as String?
      val city = list[8] as String?
      val postalCode = list[9] as String?
      val subAdministrativeArea = list[10] as String?
      val administrativeArea = list[11] as String?
      val country = list[12] as String?
      val countryCode = list[13] as String?
      return ApplePayContactDTO(phoneNumber, emailAddress, givenName, familyName, phoneticGivenName, phoneticFamilyName, addressLines, subLocality, city, postalCode, subAdministrativeArea, administrativeArea, country, countryCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      phoneNumber,
      emailAddress,
      givenName,
      familyName,
      phoneticGivenName,
      phoneticFamilyName,
      addressLines,
      subLocality,
      city,
      postalCode,
      subAdministrativeArea,
      administrativeArea,
      country,
      countryCode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApplePayShippingMethodDTO (
  val label: String,
  val detail: String,
  val amount: AmountDTO,
  val identifier: String,
  val startDate: String? = null,
  val endDate: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ApplePayShippingMethodDTO {
      val label = list[0] as String
      val detail = list[1] as String
      val amount = AmountDTO.fromList(list[2] as List<Any?>)
      val identifier = list[3] as String
      val startDate = list[4] as String?
      val endDate = list[5] as String?
      return ApplePayShippingMethodDTO(label, detail, amount, identifier, startDate, endDate)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      label,
      detail,
      amount.toList(),
      identifier,
      startDate,
      endDate,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApplePaySummaryItemDTO (
  val label: String,
  val amount: AmountDTO,
  val type: ApplePaySummaryItemType

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ApplePaySummaryItemDTO {
      val label = list[0] as String
      val amount = AmountDTO.fromList(list[1] as List<Any?>)
      val type = ApplePaySummaryItemType.ofRaw(list[2] as Int)!!
      return ApplePaySummaryItemDTO(label, amount, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      label,
      amount.toList(),
      type.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GooglePayConfigurationDTO (
  val googlePayEnvironment: GooglePayEnvironment,
  val merchantAccount: String? = null,
  val merchantInfoDTO: MerchantInfoDTO? = null,
  val totalPriceStatus: TotalPriceStatus? = null,
  val allowedCardNetworks: List<String?>? = null,
  val allowedAuthMethods: List<String?>? = null,
  val allowPrepaidCards: Boolean? = null,
  val allowCreditCards: Boolean? = null,
  val assuranceDetailsRequired: Boolean? = null,
  val emailRequired: Boolean? = null,
  val existingPaymentMethodRequired: Boolean? = null,
  val shippingAddressRequired: Boolean? = null,
  val shippingAddressParametersDTO: ShippingAddressParametersDTO? = null,
  val billingAddressRequired: Boolean? = null,
  val billingAddressParametersDTO: BillingAddressParametersDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): GooglePayConfigurationDTO {
      val googlePayEnvironment = GooglePayEnvironment.ofRaw(list[0] as Int)!!
      val merchantAccount = list[1] as String?
      val merchantInfoDTO: MerchantInfoDTO? = (list[2] as List<Any?>?)?.let {
        MerchantInfoDTO.fromList(it)
      }
      val totalPriceStatus: TotalPriceStatus? = (list[3] as Int?)?.let {
        TotalPriceStatus.ofRaw(it)
      }
      val allowedCardNetworks = list[4] as List<String?>?
      val allowedAuthMethods = list[5] as List<String?>?
      val allowPrepaidCards = list[6] as Boolean?
      val allowCreditCards = list[7] as Boolean?
      val assuranceDetailsRequired = list[8] as Boolean?
      val emailRequired = list[9] as Boolean?
      val existingPaymentMethodRequired = list[10] as Boolean?
      val shippingAddressRequired = list[11] as Boolean?
      val shippingAddressParametersDTO: ShippingAddressParametersDTO? = (list[12] as List<Any?>?)?.let {
        ShippingAddressParametersDTO.fromList(it)
      }
      val billingAddressRequired = list[13] as Boolean?
      val billingAddressParametersDTO: BillingAddressParametersDTO? = (list[14] as List<Any?>?)?.let {
        BillingAddressParametersDTO.fromList(it)
      }
      return GooglePayConfigurationDTO(googlePayEnvironment, merchantAccount, merchantInfoDTO, totalPriceStatus, allowedCardNetworks, allowedAuthMethods, allowPrepaidCards, allowCreditCards, assuranceDetailsRequired, emailRequired, existingPaymentMethodRequired, shippingAddressRequired, shippingAddressParametersDTO, billingAddressRequired, billingAddressParametersDTO)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      googlePayEnvironment.raw,
      merchantAccount,
      merchantInfoDTO?.toList(),
      totalPriceStatus?.raw,
      allowedCardNetworks,
      allowedAuthMethods,
      allowPrepaidCards,
      allowCreditCards,
      assuranceDetailsRequired,
      emailRequired,
      existingPaymentMethodRequired,
      shippingAddressRequired,
      shippingAddressParametersDTO?.toList(),
      billingAddressRequired,
      billingAddressParametersDTO?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MerchantInfoDTO (
  val merchantName: String? = null,
  val merchantId: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MerchantInfoDTO {
      val merchantName = list[0] as String?
      val merchantId = list[1] as String?
      return MerchantInfoDTO(merchantName, merchantId)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      merchantName,
      merchantId,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ShippingAddressParametersDTO (
  val allowedCountryCodes: List<String?>? = null,
  val isPhoneNumberRequired: Boolean? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ShippingAddressParametersDTO {
      val allowedCountryCodes = list[0] as List<String?>?
      val isPhoneNumberRequired = list[1] as Boolean?
      return ShippingAddressParametersDTO(allowedCountryCodes, isPhoneNumberRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      allowedCountryCodes,
      isPhoneNumberRequired,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BillingAddressParametersDTO (
  val format: String? = null,
  val isPhoneNumberRequired: Boolean? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BillingAddressParametersDTO {
      val format = list[0] as String?
      val isPhoneNumberRequired = list[1] as Boolean?
      return BillingAddressParametersDTO(format, isPhoneNumberRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      format,
      isPhoneNumberRequired,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CashAppPayConfigurationDTO (
  val cashAppPayEnvironment: CashAppPayEnvironment,
  val returnUrl: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): CashAppPayConfigurationDTO {
      val cashAppPayEnvironment = CashAppPayEnvironment.ofRaw(list[0] as Int)!!
      val returnUrl = list[1] as String
      return CashAppPayConfigurationDTO(cashAppPayEnvironment, returnUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      cashAppPayEnvironment.raw,
      returnUrl,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentResultDTO (
  val type: PaymentResultEnum,
  val reason: String? = null,
  val result: PaymentResultModelDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PaymentResultDTO {
      val type = PaymentResultEnum.ofRaw(list[0] as Int)!!
      val reason = list[1] as String?
      val result: PaymentResultModelDTO? = (list[2] as List<Any?>?)?.let {
        PaymentResultModelDTO.fromList(it)
      }
      return PaymentResultDTO(type, reason, result)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type.raw,
      reason,
      result?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentResultModelDTO (
  val sessionId: String? = null,
  val sessionData: String? = null,
  val sessionResult: String? = null,
  val resultCode: String? = null,
  val order: OrderResponseDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PaymentResultModelDTO {
      val sessionId = list[0] as String?
      val sessionData = list[1] as String?
      val sessionResult = list[2] as String?
      val resultCode = list[3] as String?
      val order: OrderResponseDTO? = (list[4] as List<Any?>?)?.let {
        OrderResponseDTO.fromList(it)
      }
      return PaymentResultModelDTO(sessionId, sessionData, sessionResult, resultCode, order)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sessionId,
      sessionData,
      sessionResult,
      resultCode,
      order?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OrderResponseDTO (
  val pspReference: String,
  val orderData: String,
  val amount: AmountDTO? = null,
  val remainingAmount: AmountDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): OrderResponseDTO {
      val pspReference = list[0] as String
      val orderData = list[1] as String
      val amount: AmountDTO? = (list[2] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      val remainingAmount: AmountDTO? = (list[3] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      return OrderResponseDTO(pspReference, orderData, amount, remainingAmount)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pspReference,
      orderData,
      amount?.toList(),
      remainingAmount?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCommunicationModel (
  val type: PlatformCommunicationType,
  val data: String? = null,
  val paymentResult: PaymentResultDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PlatformCommunicationModel {
      val type = PlatformCommunicationType.ofRaw(list[0] as Int)!!
      val data = list[1] as String?
      val paymentResult: PaymentResultDTO? = (list[2] as List<Any?>?)?.let {
        PaymentResultDTO.fromList(it)
      }
      return PlatformCommunicationModel(type, data, paymentResult)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type.raw,
      data,
      paymentResult?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ComponentCommunicationModel (
  val type: ComponentCommunicationType,
  val componentId: String,
  val data: Any? = null,
  val paymentResult: PaymentResultDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ComponentCommunicationModel {
      val type = ComponentCommunicationType.ofRaw(list[0] as Int)!!
      val componentId = list[1] as String
      val data = list[2]
      val paymentResult: PaymentResultDTO? = (list[3] as List<Any?>?)?.let {
        PaymentResultDTO.fromList(it)
      }
      return ComponentCommunicationModel(type, componentId, data, paymentResult)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type.raw,
      componentId,
      data,
      paymentResult?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentEventDTO (
  val paymentEventType: PaymentEventType,
  val result: String? = null,
  val data: Map<String?, Any?>? = null,
  val error: ErrorDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PaymentEventDTO {
      val paymentEventType = PaymentEventType.ofRaw(list[0] as Int)!!
      val result = list[1] as String?
      val data = list[2] as Map<String?, Any?>?
      val error: ErrorDTO? = (list[3] as List<Any?>?)?.let {
        ErrorDTO.fromList(it)
      }
      return PaymentEventDTO(paymentEventType, result, data, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      paymentEventType.raw,
      result,
      data,
      error?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ErrorDTO (
  val errorMessage: String? = null,
  val reason: String? = null,
  val dismissDropIn: Boolean? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ErrorDTO {
      val errorMessage = list[0] as String?
      val reason = list[1] as String?
      val dismissDropIn = list[2] as Boolean?
      return ErrorDTO(errorMessage, reason, dismissDropIn)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      errorMessage,
      reason,
      dismissDropIn,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeletedStoredPaymentMethodResultDTO (
  val storedPaymentMethodId: String,
  val isSuccessfullyRemoved: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeletedStoredPaymentMethodResultDTO {
      val storedPaymentMethodId = list[0] as String
      val isSuccessfullyRemoved = list[1] as Boolean
      return DeletedStoredPaymentMethodResultDTO(storedPaymentMethodId, isSuccessfullyRemoved)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      storedPaymentMethodId,
      isSuccessfullyRemoved,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CardComponentConfigurationDTO (
  val environment: Environment,
  val clientKey: String,
  val countryCode: String,
  val amount: AmountDTO? = null,
  val shopperLocale: String? = null,
  val cardConfiguration: CardConfigurationDTO,
  val analyticsOptionsDTO: AnalyticsOptionsDTO

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): CardComponentConfigurationDTO {
      val environment = Environment.ofRaw(list[0] as Int)!!
      val clientKey = list[1] as String
      val countryCode = list[2] as String
      val amount: AmountDTO? = (list[3] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      val shopperLocale = list[4] as String?
      val cardConfiguration = CardConfigurationDTO.fromList(list[5] as List<Any?>)
      val analyticsOptionsDTO = AnalyticsOptionsDTO.fromList(list[6] as List<Any?>)
      return CardComponentConfigurationDTO(environment, clientKey, countryCode, amount, shopperLocale, cardConfiguration, analyticsOptionsDTO)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      environment.raw,
      clientKey,
      countryCode,
      amount?.toList(),
      shopperLocale,
      cardConfiguration.toList(),
      analyticsOptionsDTO.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstantPaymentConfigurationDTO (
  val instantPaymentType: InstantPaymentType,
  val environment: Environment,
  val clientKey: String,
  val countryCode: String,
  val amount: AmountDTO? = null,
  val shopperLocale: String? = null,
  val analyticsOptionsDTO: AnalyticsOptionsDTO,
  val googlePayConfigurationDTO: GooglePayConfigurationDTO? = null,
  val applePayConfigurationDTO: ApplePayConfigurationDTO? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): InstantPaymentConfigurationDTO {
      val instantPaymentType = InstantPaymentType.ofRaw(list[0] as Int)!!
      val environment = Environment.ofRaw(list[1] as Int)!!
      val clientKey = list[2] as String
      val countryCode = list[3] as String
      val amount: AmountDTO? = (list[4] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      val shopperLocale = list[5] as String?
      val analyticsOptionsDTO = AnalyticsOptionsDTO.fromList(list[6] as List<Any?>)
      val googlePayConfigurationDTO: GooglePayConfigurationDTO? = (list[7] as List<Any?>?)?.let {
        GooglePayConfigurationDTO.fromList(it)
      }
      val applePayConfigurationDTO: ApplePayConfigurationDTO? = (list[8] as List<Any?>?)?.let {
        ApplePayConfigurationDTO.fromList(it)
      }
      return InstantPaymentConfigurationDTO(instantPaymentType, environment, clientKey, countryCode, amount, shopperLocale, analyticsOptionsDTO, googlePayConfigurationDTO, applePayConfigurationDTO)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      instantPaymentType.raw,
      environment.raw,
      clientKey,
      countryCode,
      amount?.toList(),
      shopperLocale,
      analyticsOptionsDTO.toList(),
      googlePayConfigurationDTO?.toList(),
      applePayConfigurationDTO?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstantPaymentSetupResultDTO (
  val instantPaymentType: InstantPaymentType,
  val isSupported: Boolean,
  val resultData: Any? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): InstantPaymentSetupResultDTO {
      val instantPaymentType = InstantPaymentType.ofRaw(list[0] as Int)!!
      val isSupported = list[1] as Boolean
      val resultData = list[2]
      return InstantPaymentSetupResultDTO(instantPaymentType, isSupported, resultData)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      instantPaymentType.raw,
      isSupported,
      resultData,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UnencryptedCardDTO (
  val cardNumber: String? = null,
  val expiryMonth: String? = null,
  val expiryYear: String? = null,
  val cvc: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): UnencryptedCardDTO {
      val cardNumber = list[0] as String?
      val expiryMonth = list[1] as String?
      val expiryYear = list[2] as String?
      val cvc = list[3] as String?
      return UnencryptedCardDTO(cardNumber, expiryMonth, expiryYear, cvc)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      cardNumber,
      expiryMonth,
      expiryYear,
      cvc,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EncryptedCardDTO (
  val encryptedCardNumber: String? = null,
  val encryptedExpiryMonth: String? = null,
  val encryptedExpiryYear: String? = null,
  val encryptedSecurityCode: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): EncryptedCardDTO {
      val encryptedCardNumber = list[0] as String?
      val encryptedExpiryMonth = list[1] as String?
      val encryptedExpiryYear = list[2] as String?
      val encryptedSecurityCode = list[3] as String?
      return EncryptedCardDTO(encryptedCardNumber, encryptedExpiryMonth, encryptedExpiryYear, encryptedSecurityCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      encryptedCardNumber,
      encryptedExpiryMonth,
      encryptedExpiryYear,
      encryptedSecurityCode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ActionComponentConfigurationDTO (
  val environment: Environment,
  val clientKey: String,
  val shopperLocale: String? = null,
  val amount: AmountDTO? = null,
  val analyticsOptionsDTO: AnalyticsOptionsDTO

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ActionComponentConfigurationDTO {
      val environment = Environment.ofRaw(list[0] as Int)!!
      val clientKey = list[1] as String
      val shopperLocale = list[2] as String?
      val amount: AmountDTO? = (list[3] as List<Any?>?)?.let {
        AmountDTO.fromList(it)
      }
      val analyticsOptionsDTO = AnalyticsOptionsDTO.fromList(list[4] as List<Any?>)
      return ActionComponentConfigurationDTO(environment, clientKey, shopperLocale, amount, analyticsOptionsDTO)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      environment.raw,
      clientKey,
      shopperLocale,
      amount?.toList(),
      analyticsOptionsDTO.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OrderCancelResultDTO (
  val orderCancelResponseBody: Map<String?, Any?>,
  val updatedPaymentMethodsResponseBody: Map<String?, Any?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): OrderCancelResultDTO {
      val orderCancelResponseBody = list[0] as Map<String?, Any?>
      val updatedPaymentMethodsResponseBody = list[1] as Map<String?, Any?>?
      return OrderCancelResultDTO(orderCancelResponseBody, updatedPaymentMethodsResponseBody)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      orderCancelResponseBody,
      updatedPaymentMethodsResponseBody,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object CheckoutPlatformInterfaceCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ActionComponentConfigurationDTO.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyticsOptionsDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayConfigurationDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayContactDTO.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayShippingMethodDTO.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePaySummaryItemDTO.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BillingAddressParametersDTO.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardComponentConfigurationDTO.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardConfigurationDTO.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CashAppPayConfigurationDTO.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ComponentCommunicationModel.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeletedStoredPaymentMethodResultDTO.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DropInConfigurationDTO.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptedCardDTO.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorDTO.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GooglePayConfigurationDTO.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstantPaymentConfigurationDTO.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstantPaymentSetupResultDTO.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MerchantInfoDTO.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderCancelResultDTO.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderResponseDTO.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentEventDTO.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultDTO.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultModelDTO.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCommunicationModel.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionDTO.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShippingAddressParametersDTO.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UnencryptedCardDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ActionComponentConfigurationDTO -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is AmountDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AnalyticsOptionsDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ApplePayConfigurationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApplePayContactDTO -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ApplePayShippingMethodDTO -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ApplePaySummaryItemDTO -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BillingAddressParametersDTO -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CardComponentConfigurationDTO -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CardConfigurationDTO -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CashAppPayConfigurationDTO -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ComponentCommunicationModel -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is DeletedStoredPaymentMethodResultDTO -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is DropInConfigurationDTO -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is EncryptedCardDTO -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ErrorDTO -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is GooglePayConfigurationDTO -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is InstantPaymentConfigurationDTO -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is InstantPaymentSetupResultDTO -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is MerchantInfoDTO -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is OrderCancelResultDTO -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is OrderResponseDTO -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is PaymentEventDTO -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is PaymentResultDTO -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is PaymentResultModelDTO -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is PlatformCommunicationModel -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is SessionDTO -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is ShippingAddressParametersDTO -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is UnencryptedCardDTO -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CheckoutPlatformInterface {
  fun getReturnUrl(callback: (Result<String>) -> Unit)
  fun createSession(sessionId: String, sessionData: String, configuration: Any?, callback: (Result<SessionDTO>) -> Unit)
  fun clearSession()
  fun encryptCard(unencryptedCardDTO: UnencryptedCardDTO, publicKey: String, callback: (Result<EncryptedCardDTO>) -> Unit)
  fun encryptBin(bin: String, publicKey: String, callback: (Result<String>) -> Unit)
  fun validateCardNumber(cardNumber: String, enableLuhnCheck: Boolean): CardNumberValidationResultDTO
  fun validateCardExpiryDate(expiryMonth: String, expiryYear: String): CardExpiryDateValidationResultDTO
  fun validateCardSecurityCode(securityCode: String, cardBrandTxVariant: String?): CardSecurityCodeValidationResultDTO
  fun enableConsoleLogging(loggingEnabled: Boolean)

  companion object {
    /** The codec used by CheckoutPlatformInterface. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutPlatformInterfaceCodec
    }
    /** Sets up an instance of `CheckoutPlatformInterface` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: CheckoutPlatformInterface?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.getReturnUrl", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getReturnUrl() { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.createSession", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val sessionDataArg = args[1] as String
            val configurationArg = args[2]
            api.createSession(sessionIdArg, sessionDataArg, configurationArg) { result: Result<SessionDTO> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.clearSession", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.clearSession()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.encryptCard", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val unencryptedCardDTOArg = args[0] as UnencryptedCardDTO
            val publicKeyArg = args[1] as String
            api.encryptCard(unencryptedCardDTOArg, publicKeyArg) { result: Result<EncryptedCardDTO> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.encryptBin", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val binArg = args[0] as String
            val publicKeyArg = args[1] as String
            api.encryptBin(binArg, publicKeyArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.validateCardNumber", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cardNumberArg = args[0] as String
            val enableLuhnCheckArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.validateCardNumber(cardNumberArg, enableLuhnCheckArg).raw)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.validateCardExpiryDate", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val expiryMonthArg = args[0] as String
            val expiryYearArg = args[1] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.validateCardExpiryDate(expiryMonthArg, expiryYearArg).raw)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.validateCardSecurityCode", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val securityCodeArg = args[0] as String
            val cardBrandTxVariantArg = args[1] as String?
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.validateCardSecurityCode(securityCodeArg, cardBrandTxVariantArg).raw)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.enableConsoleLogging", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val loggingEnabledArg = args[0] as Boolean
            var wrapped: List<Any?>
            try {
              api.enableConsoleLogging(loggingEnabledArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object DropInPlatformInterfaceCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyticsOptionsDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayConfigurationDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayContactDTO.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayShippingMethodDTO.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePaySummaryItemDTO.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BillingAddressParametersDTO.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardConfigurationDTO.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CashAppPayConfigurationDTO.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeletedStoredPaymentMethodResultDTO.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DropInConfigurationDTO.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorDTO.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GooglePayConfigurationDTO.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MerchantInfoDTO.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderCancelResultDTO.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentEventDTO.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShippingAddressParametersDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AmountDTO -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is AmountDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AnalyticsOptionsDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ApplePayConfigurationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApplePayContactDTO -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ApplePayShippingMethodDTO -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ApplePaySummaryItemDTO -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BillingAddressParametersDTO -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CardConfigurationDTO -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CashAppPayConfigurationDTO -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is DeletedStoredPaymentMethodResultDTO -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is DropInConfigurationDTO -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is ErrorDTO -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is GooglePayConfigurationDTO -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is MerchantInfoDTO -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is OrderCancelResultDTO -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is PaymentEventDTO -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ShippingAddressParametersDTO -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DropInPlatformInterface {
  fun showDropInSession(dropInConfigurationDTO: DropInConfigurationDTO)
  fun showDropInAdvanced(dropInConfigurationDTO: DropInConfigurationDTO, paymentMethodsResponse: String)
  fun onPaymentsResult(paymentsResult: PaymentEventDTO)
  fun onPaymentsDetailsResult(paymentsDetailsResult: PaymentEventDTO)
  fun onDeleteStoredPaymentMethodResult(deleteStoredPaymentMethodResultDTO: DeletedStoredPaymentMethodResultDTO)
  fun onBalanceCheckResult(balanceCheckResponse: String)
  fun onOrderRequestResult(orderRequestResponse: String)
  fun onOrderCancelResult(orderCancelResult: OrderCancelResultDTO)
  fun cleanUpDropIn()

  companion object {
    /** The codec used by DropInPlatformInterface. */
    val codec: MessageCodec<Any?> by lazy {
      DropInPlatformInterfaceCodec
    }
    /** Sets up an instance of `DropInPlatformInterface` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: DropInPlatformInterface?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.showDropInSession", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dropInConfigurationDTOArg = args[0] as DropInConfigurationDTO
            var wrapped: List<Any?>
            try {
              api.showDropInSession(dropInConfigurationDTOArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.showDropInAdvanced", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dropInConfigurationDTOArg = args[0] as DropInConfigurationDTO
            val paymentMethodsResponseArg = args[1] as String
            var wrapped: List<Any?>
            try {
              api.showDropInAdvanced(dropInConfigurationDTOArg, paymentMethodsResponseArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onPaymentsResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paymentsResultArg = args[0] as PaymentEventDTO
            var wrapped: List<Any?>
            try {
              api.onPaymentsResult(paymentsResultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onPaymentsDetailsResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paymentsDetailsResultArg = args[0] as PaymentEventDTO
            var wrapped: List<Any?>
            try {
              api.onPaymentsDetailsResult(paymentsDetailsResultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onDeleteStoredPaymentMethodResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deleteStoredPaymentMethodResultDTOArg = args[0] as DeletedStoredPaymentMethodResultDTO
            var wrapped: List<Any?>
            try {
              api.onDeleteStoredPaymentMethodResult(deleteStoredPaymentMethodResultDTOArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onBalanceCheckResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val balanceCheckResponseArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.onBalanceCheckResult(balanceCheckResponseArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onOrderRequestResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val orderRequestResponseArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.onOrderRequestResult(orderRequestResponseArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.onOrderCancelResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val orderCancelResultArg = args[0] as OrderCancelResultDTO
            var wrapped: List<Any?>
            try {
              api.onOrderCancelResult(orderCancelResultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.DropInPlatformInterface.cleanUpDropIn", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.cleanUpDropIn()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object DropInFlutterInterfaceCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderResponseDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultModelDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCommunicationModel.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AmountDTO -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is OrderResponseDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PaymentResultDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PaymentResultModelDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PlatformCommunicationModel -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class DropInFlutterInterface(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by DropInFlutterInterface. */
    val codec: MessageCodec<Any?> by lazy {
      DropInFlutterInterfaceCodec
    }
  }
  fun onDropInSessionPlatformCommunication(platformCommunicationModelArg: PlatformCommunicationModel, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.adyen_checkout.DropInFlutterInterface.onDropInSessionPlatformCommunication"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(platformCommunicationModelArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AdyenPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDropInAdvancedPlatformCommunication(platformCommunicationModelArg: PlatformCommunicationModel, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.adyen_checkout.DropInFlutterInterface.onDropInAdvancedPlatformCommunication"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(platformCommunicationModelArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AdyenPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object ComponentPlatformInterfaceCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ActionComponentConfigurationDTO.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyticsOptionsDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayConfigurationDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayContactDTO.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePayShippingMethodDTO.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApplePaySummaryItemDTO.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BillingAddressParametersDTO.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardComponentConfigurationDTO.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardConfigurationDTO.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CashAppPayConfigurationDTO.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ComponentCommunicationModel.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeletedStoredPaymentMethodResultDTO.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DropInConfigurationDTO.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptedCardDTO.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorDTO.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GooglePayConfigurationDTO.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstantPaymentConfigurationDTO.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstantPaymentSetupResultDTO.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MerchantInfoDTO.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderCancelResultDTO.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderResponseDTO.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentEventDTO.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultDTO.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultModelDTO.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCommunicationModel.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionDTO.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShippingAddressParametersDTO.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UnencryptedCardDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ActionComponentConfigurationDTO -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is AmountDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AnalyticsOptionsDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ApplePayConfigurationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApplePayContactDTO -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ApplePayShippingMethodDTO -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ApplePaySummaryItemDTO -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BillingAddressParametersDTO -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CardComponentConfigurationDTO -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CardConfigurationDTO -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CashAppPayConfigurationDTO -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ComponentCommunicationModel -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is DeletedStoredPaymentMethodResultDTO -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is DropInConfigurationDTO -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is EncryptedCardDTO -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ErrorDTO -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is GooglePayConfigurationDTO -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is InstantPaymentConfigurationDTO -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is InstantPaymentSetupResultDTO -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is MerchantInfoDTO -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is OrderCancelResultDTO -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is OrderResponseDTO -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is PaymentEventDTO -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is PaymentResultDTO -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is PaymentResultModelDTO -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is PlatformCommunicationModel -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is SessionDTO -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is ShippingAddressParametersDTO -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is UnencryptedCardDTO -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ComponentPlatformInterface {
  fun updateViewHeight(viewId: Long)
  fun onPaymentsResult(componentId: String, paymentsResult: PaymentEventDTO)
  fun onPaymentsDetailsResult(componentId: String, paymentsDetailsResult: PaymentEventDTO)
  fun isInstantPaymentSupportedByPlatform(instantPaymentConfigurationDTO: InstantPaymentConfigurationDTO, paymentMethodResponse: String, componentId: String, callback: (Result<InstantPaymentSetupResultDTO>) -> Unit)
  fun onInstantPaymentPressed(instantPaymentConfigurationDTO: InstantPaymentConfigurationDTO, encodedPaymentMethod: String, componentId: String)
  fun handleAction(actionComponentConfiguration: ActionComponentConfigurationDTO, componentId: String, actionResponse: Map<String?, Any?>?)
  fun onDispose(componentId: String)

  companion object {
    /** The codec used by ComponentPlatformInterface. */
    val codec: MessageCodec<Any?> by lazy {
      ComponentPlatformInterfaceCodec
    }
    /** Sets up an instance of `ComponentPlatformInterface` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: ComponentPlatformInterface?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.updateViewHeight", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.updateViewHeight(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.onPaymentsResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentIdArg = args[0] as String
            val paymentsResultArg = args[1] as PaymentEventDTO
            var wrapped: List<Any?>
            try {
              api.onPaymentsResult(componentIdArg, paymentsResultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.onPaymentsDetailsResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentIdArg = args[0] as String
            val paymentsDetailsResultArg = args[1] as PaymentEventDTO
            var wrapped: List<Any?>
            try {
              api.onPaymentsDetailsResult(componentIdArg, paymentsDetailsResultArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.isInstantPaymentSupportedByPlatform", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instantPaymentConfigurationDTOArg = args[0] as InstantPaymentConfigurationDTO
            val paymentMethodResponseArg = args[1] as String
            val componentIdArg = args[2] as String
            api.isInstantPaymentSupportedByPlatform(instantPaymentConfigurationDTOArg, paymentMethodResponseArg, componentIdArg) { result: Result<InstantPaymentSetupResultDTO> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.onInstantPaymentPressed", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instantPaymentConfigurationDTOArg = args[0] as InstantPaymentConfigurationDTO
            val encodedPaymentMethodArg = args[1] as String
            val componentIdArg = args[2] as String
            var wrapped: List<Any?>
            try {
              api.onInstantPaymentPressed(instantPaymentConfigurationDTOArg, encodedPaymentMethodArg, componentIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.handleAction", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionComponentConfigurationArg = args[0] as ActionComponentConfigurationDTO
            val componentIdArg = args[1] as String
            val actionResponseArg = args[2] as Map<String?, Any?>?
            var wrapped: List<Any?>
            try {
              api.handleAction(actionComponentConfigurationArg, componentIdArg, actionResponseArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.adyen_checkout.ComponentPlatformInterface.onDispose", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.onDispose(componentIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object ComponentFlutterInterfaceCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AmountDTO.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyticsOptionsDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardComponentConfigurationDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardConfigurationDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ComponentCommunicationModel.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrderResponseDTO.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultDTO.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultModelDTO.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AmountDTO -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is AnalyticsOptionsDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CardComponentConfigurationDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CardConfigurationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ComponentCommunicationModel -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is OrderResponseDTO -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PaymentResultDTO -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PaymentResultModelDTO -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is SessionDTO -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class ComponentFlutterInterface(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by ComponentFlutterInterface. */
    val codec: MessageCodec<Any?> by lazy {
      ComponentFlutterInterfaceCodec
    }
  }
  fun _generateCodecForDTOs(cardComponentConfigurationDTOArg: CardComponentConfigurationDTO, sessionDTOArg: SessionDTO, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.adyen_checkout.ComponentFlutterInterface._generateCodecForDTOs"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cardComponentConfigurationDTOArg, sessionDTOArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AdyenPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onComponentCommunication(componentCommunicationModelArg: ComponentCommunicationModel, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.adyen_checkout.ComponentFlutterInterface.onComponentCommunication"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(componentCommunicationModelArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AdyenPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
