// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum Environment: Int {
  case test = 0
  case europe = 1
  case unitedStates = 2
  case australia = 3
  case india = 4
  case apse = 5
}

enum Locale: Int {
  case canada = 0
  case canadaFrench = 1
  case china = 2
  case chinese = 3
  case english = 4
  case france = 5
  case french = 6
  case german = 7
  case germany = 8
  case italian = 9
  case italy = 10
  case japan = 11
  case japanese = 12
  case korea = 13
  case korean = 14
  case prc = 15
  case root = 16
  case simplifiedChinese = 17
  case taiwan = 18
  case traditionalChinese = 19
  case uk = 20
  case us = 21
}

enum SessionDropInResultEnum: Int {
  case cancelledByUser = 0
  case error = 1
  case finished = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionModel {
  var id: String
  var sessionData: String

  static func fromList(_ list: [Any?]) -> SessionModel? {
    let id = list[0] as! String
    let sessionData = list[1] as! String

    return SessionModel(
      id: id,
      sessionData: sessionData
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      sessionData,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Amount {
  var currency: String
  var value: Double

  static func fromList(_ list: [Any?]) -> Amount? {
    let currency = list[0] as! String
    let value = list[1] as! Double

    return Amount(
      currency: currency,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      currency,
      value,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DropInConfiguration {
  var shopperLocale: Locale? = nil
  var environment: Environment
  var clientKey: String
  var amount: Amount
  var isAnalyticsEnabled: Bool? = nil
  var showPreselectedStoredPaymentMethod: Bool? = nil
  var skipListWhenSinglePaymentMethod: Bool? = nil
  var isRemovingStoredPaymentMethodsEnabled: Bool? = nil
  var additionalDataForDropInService: String? = nil

  static func fromList(_ list: [Any?]) -> DropInConfiguration? {
    var shopperLocale: Locale? = nil
    let shopperLocaleEnumVal: Int? = nilOrValue(list[0])
    if let shopperLocaleRawValue = shopperLocaleEnumVal {
      shopperLocale = Locale(rawValue: shopperLocaleRawValue)!
    }
    let environment = Environment(rawValue: list[1] as! Int)!
    let clientKey = list[2] as! String
    let amount = Amount.fromList(list[3] as! [Any?])!
    let isAnalyticsEnabled: Bool? = nilOrValue(list[4])
    let showPreselectedStoredPaymentMethod: Bool? = nilOrValue(list[5])
    let skipListWhenSinglePaymentMethod: Bool? = nilOrValue(list[6])
    let isRemovingStoredPaymentMethodsEnabled: Bool? = nilOrValue(list[7])
    let additionalDataForDropInService: String? = nilOrValue(list[8])

    return DropInConfiguration(
      shopperLocale: shopperLocale,
      environment: environment,
      clientKey: clientKey,
      amount: amount,
      isAnalyticsEnabled: isAnalyticsEnabled,
      showPreselectedStoredPaymentMethod: showPreselectedStoredPaymentMethod,
      skipListWhenSinglePaymentMethod: skipListWhenSinglePaymentMethod,
      isRemovingStoredPaymentMethodsEnabled: isRemovingStoredPaymentMethodsEnabled,
      additionalDataForDropInService: additionalDataForDropInService
    )
  }
  func toList() -> [Any?] {
    return [
      shopperLocale?.rawValue,
      environment.rawValue,
      clientKey,
      amount.toList(),
      isAnalyticsEnabled,
      showPreselectedStoredPaymentMethod,
      skipListWhenSinglePaymentMethod,
      isRemovingStoredPaymentMethodsEnabled,
      additionalDataForDropInService,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionDropInResult {
  var sessionDropInResult: SessionDropInResultEnum
  var data: String

  static func fromList(_ list: [Any?]) -> SessionDropInResult? {
    let sessionDropInResult = SessionDropInResultEnum(rawValue: list[0] as! Int)!
    let data = list[1] as! String

    return SessionDropInResult(
      sessionDropInResult: sessionDropInResult,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      sessionDropInResult.rawValue,
      data,
    ]
  }
}

private class DropInSessionsApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return Amount.fromList(self.readValue() as! [Any?])
      case 129:
        return DropInConfiguration.fromList(self.readValue() as! [Any?])
      case 130:
        return SessionModel.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class DropInSessionsApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Amount {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? DropInConfiguration {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SessionModel {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DropInSessionsApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DropInSessionsApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DropInSessionsApiCodecWriter(data: data)
  }
}

class DropInSessionsApiCodec: FlutterStandardMessageCodec {
  static let shared = DropInSessionsApiCodec(readerWriter: DropInSessionsApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DropInSessionsApi {
  func startPayment(sessionModel: SessionModel, dropInConfiguration: DropInConfiguration, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DropInSessionsApiSetup {
  /// The codec used by DropInSessionsApi.
  static var codec: FlutterStandardMessageCodec { DropInSessionsApiCodec.shared }
  /// Sets up an instance of `DropInSessionsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DropInSessionsApi?) {
    let startPaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.adyen_checkout.DropInSessionsApi.startPayment", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionModelArg = args[0] as! SessionModel
        let dropInConfigurationArg = args[1] as! DropInConfiguration
        api.startPayment(sessionModel: sessionModelArg, dropInConfiguration: dropInConfigurationArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      startPaymentChannel.setMessageHandler(nil)
    }
  }
}
private class FlutterCommunicationApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return SessionDropInResult.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class FlutterCommunicationApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SessionDropInResult {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterCommunicationApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterCommunicationApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterCommunicationApiCodecWriter(data: data)
  }
}

class FlutterCommunicationApiCodec: FlutterStandardMessageCodec {
  static let shared = FlutterCommunicationApiCodec(readerWriter: FlutterCommunicationApiCodecReaderWriter())
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FlutterCommunicationApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return FlutterCommunicationApiCodec.shared
  }
  func onDropInResult(sessionDropInResult sessionDropInResultArg: SessionDropInResult, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.adyen_checkout.FlutterCommunicationApi.onDropInResult", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionDropInResultArg] as [Any?]) { _ in
      completion()
    }
  }
}
