disabled_rules:
  - todo
  - type_name
  - trailing_whitespace

excluded:
  - adyen_checkout/Sources/adyen_checkout/generated/PlatformApi.swift

line_length:
  ignores_function_declarations: true
  ignores_urls: true
  warning: 140

file_length:
  warning: 500

function_parameter_count:
  warning: 6

identifier_name:
  max_length:
    warning: 50

reporter: "json"