name: Android ui tests

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  android_ui_tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Provide more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm      

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - run: flutter pub get
      - run: dart pub global activate patrol_cli
      - run: patrol doctor

      - name: Boot emulator or run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          working-directory: ./example
          script: |
            echo "Emulator launched"
            pwd
            ls
            patrol doctor
            patrol test -t integration_test/drop_in_test/open_drop_in_test.dart -d emulator-5554


#        TODO Add github environment values
#      - run: patrol test -t example/integration_test/drop_in_test/open_drop_in_test.dart -d 'iPhone 15'