name: Android ui tests

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  android_ui_tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Provide more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - run: flutter pub get
      - run: dart pub global activate patrol_cli
      - run: patrol doctor

      - name: Boot emulator or run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            echo "Emulator launched"
            patrol test -t example/integration_test/drop_in_test/open_drop_in_test.dart -d 'iPhone 15'


#        TODO Add github environment values
#      - run: patrol test -t example/integration_test/drop_in_test/open_drop_in_test.dart -d 'iPhone 15'