name: Clean build test

on:
  workflow_dispatch:
  pull_request:
    branches:
     - main
    types:
     - closed
  push:
    tags:
      - '*'

jobs:
  android_clean_build_test:
    name: Android clean build test
    uses: ./.github/workflows/android_clean_build.yml

  ios_clean_build_test:
    name: iOS clean build tests
    uses: ./.github/workflows/ios_clean_build.yml

