name: Clean build test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  android_clean_build_test:
    name: Android clean build test
    uses: ./.github/workflows/android_clean_build.yml

  ios_clean_build_test:
    name: iOS clean build tests
    uses: ./.github/workflows/ios_clean_build.yml

  ios_spm_build_test:
    name: iOS SPM test
    uses: ./.github/workflows/ios_spm_build.yml

