name: Flutter unit tests

on:
  workflow_call

jobs:
  android_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
          cache: true

      - run: flutter doctor -v
      - run: flutter pub get
      - run: dart analyze
      - run: flutter test
