name: iOS clean build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - addCleaniOSBuild
    tags:
      - '*'

jobs:
  iOS_clean_build:
    runs-on: macos-14
    strategy:
      matrix:
        iPhone: ["'iPhone 15'"]
        flutter-version: [ "3.24.0" ]

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ matrix.flutter-version }}

      - run: flutter pub get

      - run: open -a Simulator && xcrun simctl boot ${{ matrix.iPhone }}

      - run: |
          flutter create --template=app --platforms=android,ios demo_project
          cd demo_project
          dart pub add 'adyen_checkout:{"path":"../"}'
          flutter build ios --debug --simulator
          xcrun simctl install ${{ matrix.iPhone }} build/ios/iphonesimulator/Runner.app
          xcrun simctl launch ${{ matrix.iPhone }} com.example.demoProject