name: iOS ui tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      flutter-version:
        description: 'Flutter version'
        required: true
        default: '3.24.0'
        type: string

jobs:
  ios_ui_tests:
    runs-on: macos-14

    steps:
      - name: Provide more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}

      - run: flutter pub get
      - run: dart pub global activate patrol_cli
      - run: patrol doctor
      - run: open -a Simulator && xcrun simctl boot 'iPhone 15'
      - run: patrol test -t example/integration_test/drop_in_test/open_drop_in_test.dart --dart-define=CLIENT_KEY='${{ secrets.ADYEN_TEST_CLIENT_KEY }}' --dart-define=X_API_KEY='${{ secrets.ADYEN_TEST_X_API_KEY }}' -d 'iPhone 15'