name: iOS ui tests

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  ios_ui_tests:
    runs-on: macos-14

    steps:
      - name: Provide more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: 'stable'
          cache: true
          cache-key: ${{ matrix.flutter-version }}

      - run: flutter pub get
      - run: dart pub global activate patrol_cli
      - run: patrol doctor
      - run: open -a Simulator && xcrun simctl boot 'iPhone 15'
#        TODO Add github environment values
#      - run: patrol test -t example/integration_test/drop_in_test/open_drop_in_test.dart -d 'iPhone 15'