# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/android
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Flutter
      - uses: ./.github/workflows/setup_flutter.yml
        with:
          flutter-version: '3.16.2'

      - name: Run script
        run: cat ./local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Init gradle wrapper
        run: gradle wrapper

      - name: Execute unit tests
        run: ./gradlew testDebugUnitTest
