# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/android
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
          cache: true

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Touch local properties
        run: touch local.properties

      - name: Add Flutter sdk path
        run: echo "flutter.sdk=/opt/hostedtoolcache/flutter" >> local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Init gradle wrapper
        run: gradle wrapper

      - name: Execute Gradle build
        run: ./gradlew build
